// Code generated by dagger-compiler.  Do not edit.
package com.mobileappdevelopersclub.fapp.ui;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<DailyScheduleFragment>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code DailyScheduleFragment} and its
 * dependencies.
 * 
 * Being a {@code Provider<DailyScheduleFragment>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<DailyScheduleFragment>} and handling injection
 * of annotated fields.
 */
public final class DailyScheduleFragment$$InjectAdapter extends Binding<DailyScheduleFragment>
    implements Provider<DailyScheduleFragment>, MembersInjector<DailyScheduleFragment> {
  private Binding<org.ektorp.CouchDbInstance> dbInstance;
  private Binding<com.mobileappdevelopersclub.fapp.FappFragment> supertype;

  public DailyScheduleFragment$$InjectAdapter() {
    super("com.mobileappdevelopersclub.fapp.ui.DailyScheduleFragment", "members/com.mobileappdevelopersclub.fapp.ui.DailyScheduleFragment", NOT_SINGLETON, DailyScheduleFragment.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    dbInstance = (Binding<org.ektorp.CouchDbInstance>) linker.requestBinding("org.ektorp.CouchDbInstance", DailyScheduleFragment.class, getClass().getClassLoader());
    supertype = (Binding<com.mobileappdevelopersclub.fapp.FappFragment>) linker.requestBinding("members/com.mobileappdevelopersclub.fapp.FappFragment", DailyScheduleFragment.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(dbInstance);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<DailyScheduleFragment>}.
   */
  @Override
  public DailyScheduleFragment get() {
    DailyScheduleFragment result = new DailyScheduleFragment();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<DailyScheduleFragment>}.
   */
  @Override
  public void injectMembers(DailyScheduleFragment object) {
    object.dbInstance = dbInstance.get();
    supertype.injectMembers(object);
  }
}
