// Code generated by dagger-compiler.  Do not edit.
package com.mobileappdevelopersclub.fapp.ui;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<ScheduleFragment>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code ScheduleFragment} and its
 * dependencies.
 * 
 * Being a {@code Provider<ScheduleFragment>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<ScheduleFragment>} and handling injection
 * of annotated fields.
 */
public final class ScheduleFragment$$InjectAdapter extends Binding<ScheduleFragment>
    implements Provider<ScheduleFragment>, MembersInjector<ScheduleFragment> {
  private Binding<org.ektorp.CouchDbInstance> dbInstance;
  private Binding<com.mobileappdevelopersclub.fapp.FappFragment> supertype;

  public ScheduleFragment$$InjectAdapter() {
    super("com.mobileappdevelopersclub.fapp.ui.ScheduleFragment", "members/com.mobileappdevelopersclub.fapp.ui.ScheduleFragment", NOT_SINGLETON, ScheduleFragment.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    dbInstance = (Binding<org.ektorp.CouchDbInstance>) linker.requestBinding("org.ektorp.CouchDbInstance", ScheduleFragment.class, getClass().getClassLoader());
    supertype = (Binding<com.mobileappdevelopersclub.fapp.FappFragment>) linker.requestBinding("members/com.mobileappdevelopersclub.fapp.FappFragment", ScheduleFragment.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(dbInstance);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<ScheduleFragment>}.
   */
  @Override
  public ScheduleFragment get() {
    ScheduleFragment result = new ScheduleFragment();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<ScheduleFragment>}.
   */
  @Override
  public void injectMembers(ScheduleFragment object) {
    object.dbInstance = dbInstance.get();
    supertype.injectMembers(object);
  }
}
